#!/usr/bin/env python3
# coding: utf-8
# -*- coding: utf-8 -*-

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QFileDialog
from excel_check import excel_check


class MyWindow(QMainWindow):
    def __init__(self):
        super(MyWindow, self).__init__()
        self.setObjectName("MainWindow")
        self.resize(640, 720)
        self.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.initUI()

    def initUI(self):
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.block_1 = QtWidgets.QFrame(self.centralwidget)
        self.block_1.setGeometry(QtCore.QRect(10, 10, 620, 155))
        self.block_1.setAccessibleName("")
        self.block_1.setAccessibleDescription("")
        self.block_1.setLocale(QtCore.QLocale(QtCore.QLocale.Polish, QtCore.QLocale.Poland))
        self.block_1.setFrameShape(QtWidgets.QFrame.Panel)
        self.block_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.block_1.setLineWidth(2)
        self.block_1.setObjectName("block_1")
        self.block_1_title = QtWidgets.QLabel(self.block_1)
        self.block_1_title.setGeometry(QtCore.QRect(10, 5, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.block_1_title.setFont(font)
        self.block_1_title.setObjectName("block_1_title")
        self.block_1_description = QtWidgets.QLabel(self.block_1)
        self.block_1_description.setGeometry(QtCore.QRect(10, 35, 600, 30))
        self.block_1_description.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.block_1_description.setFrameShape(QtWidgets.QFrame.Panel)
        self.block_1_description.setFrameShadow(QtWidgets.QFrame.Raised)
        self.block_1_description.setObjectName("block_1_description")
        self.bom_button = QtWidgets.QPushButton(self.block_1)
        self.bom_button.setGeometry(QtCore.QRect(10, 80, 80, 25))
        self.bom_button.setObjectName("bom_button")
        self.bom_verification_button = QtWidgets.QPushButton(self.block_1)
        self.bom_verification_button.setGeometry(QtCore.QRect(10, 120, 200, 25))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bom_verification_button.setFont(font)
        self.bom_verification_button.setDefault(True)
        self.bom_verification_button.setObjectName("bom_verification_button")
        self.line_bom_path = QtWidgets.QLineEdit(self.block_1)
        self.line_bom_path.setGeometry(QtCore.QRect(90, 80, 520, 25))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setItalic(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.line_bom_path.setFont(font)
        self.line_bom_path.setInputMask("")
        self.line_bom_path.setText("Nie wybrano pliku.")
        self.line_bom_path.setMaxLength(32773)
        self.line_bom_path.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_bom_path.setReadOnly(True)
        self.line_bom_path.setObjectName("line_bom_path")
        self.bom_verification_info_text = QtWidgets.QLabel(self.block_1)
        self.bom_verification_info_text.setGeometry(QtCore.QRect(220, 120, 390, 25))
        self.bom_verification_info_text.setObjectName("bom_verification_info_text")
        self.block_2 = QtWidgets.QFrame(self.centralwidget)
        self.block_2.setGeometry(QtCore.QRect(10, 170, 620, 120))
        self.block_2.setAccessibleName("")
        self.block_2.setAccessibleDescription("")
        self.block_2.setLocale(QtCore.QLocale(QtCore.QLocale.Polish, QtCore.QLocale.Poland))
        self.block_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.block_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.block_2.setLineWidth(2)
        self.block_2.setObjectName("block_2")
        self.block_2_title = QtWidgets.QLabel(self.block_2)
        self.block_2_title.setGeometry(QtCore.QRect(10, 5, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.block_2_title.setFont(font)
        self.block_2_title.setObjectName("block_2_title")
        self.block_2_description = QtWidgets.QLabel(self.block_2)
        self.block_2_description.setGeometry(QtCore.QRect(10, 35, 600, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.block_2_description.sizePolicy().hasHeightForWidth())
        self.block_2_description.setSizePolicy(sizePolicy)
        self.block_2_description.setMinimumSize(QtCore.QSize(0, 30))
        self.block_2_description.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.block_2_description.setFrameShape(QtWidgets.QFrame.Panel)
        self.block_2_description.setFrameShadow(QtWidgets.QFrame.Raised)
        self.block_2_description.setTextFormat(QtCore.Qt.AutoText)
        self.block_2_description.setScaledContents(False)
        self.block_2_description.setWordWrap(True)
        self.block_2_description.setObjectName("block_2_description")
        self.qty_calculation_button = QtWidgets.QPushButton(self.block_2)
        self.qty_calculation_button.setGeometry(QtCore.QRect(10, 85, 200, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.qty_calculation_button.setFont(font)
        self.qty_calculation_button.setDefault(True)
        self.qty_calculation_button.setObjectName("qty_calculation_button")
        self.bom_verification_info_text_2 = QtWidgets.QLabel(self.block_2)
        self.bom_verification_info_text_2.setGeometry(QtCore.QRect(220, 85, 390, 25))
        self.bom_verification_info_text_2.setObjectName("bom_verification_info_text_2")
        self.block_3 = QtWidgets.QFrame(self.centralwidget)
        self.block_3.setGeometry(QtCore.QRect(10, 295, 620, 120))
        self.block_3.setAccessibleName("")
        self.block_3.setAccessibleDescription("")
        self.block_3.setLocale(QtCore.QLocale(QtCore.QLocale.Polish, QtCore.QLocale.Poland))
        self.block_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.block_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.block_3.setLineWidth(2)
        self.block_3.setObjectName("block_3")
        self.block_3_title = QtWidgets.QLabel(self.block_3)
        self.block_3_title.setGeometry(QtCore.QRect(10, 5, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.block_3_title.setFont(font)
        self.block_3_title.setObjectName("block_3_title")
        self.block_3_description = QtWidgets.QLabel(self.block_3)
        self.block_3_description.setGeometry(QtCore.QRect(10, 35, 600, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.block_3_description.sizePolicy().hasHeightForWidth())
        self.block_3_description.setSizePolicy(sizePolicy)
        self.block_3_description.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.block_3_description.setFrameShape(QtWidgets.QFrame.Panel)
        self.block_3_description.setFrameShadow(QtWidgets.QFrame.Raised)
        self.block_3_description.setObjectName("block_3_description")
        self.button_destination_path = QtWidgets.QPushButton(self.block_3)
        self.button_destination_path.setGeometry(QtCore.QRect(530, 80, 80, 25))
        self.button_destination_path.setDefault(True)
        self.button_destination_path.setObjectName("button_destination_path")
        self.line_destination_path = QtWidgets.QLineEdit(self.block_3)
        self.line_destination_path.setGeometry(QtCore.QRect(10, 80, 520, 25))
        self.line_destination_path.setInputMask("")
        self.line_destination_path.setReadOnly(True)
        self.line_destination_path.setObjectName("line_destination_path")
        self.block_4 = QtWidgets.QFrame(self.centralwidget)
        self.block_4.setGeometry(QtCore.QRect(10, 420, 620, 120))
        self.block_4.setAccessibleName("")
        self.block_4.setAccessibleDescription("")
        self.block_4.setLocale(QtCore.QLocale(QtCore.QLocale.Polish, QtCore.QLocale.Poland))
        self.block_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.block_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.block_4.setLineWidth(2)
        self.block_4.setObjectName("block_4")
        self.block_4_title = QtWidgets.QLabel(self.block_4)
        self.block_4_title.setGeometry(QtCore.QRect(10, 5, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.block_4_title.setFont(font)
        self.block_4_title.setObjectName("block_4_title")
        self.block_4_description = QtWidgets.QLabel(self.block_4)
        self.block_4_description.setGeometry(QtCore.QRect(10, 35, 600, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.block_4_description.sizePolicy().hasHeightForWidth())
        self.block_4_description.setSizePolicy(sizePolicy)
        self.block_4_description.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.block_4_description.setFrameShape(QtWidgets.QFrame.Panel)
        self.block_4_description.setFrameShadow(QtWidgets.QFrame.Raised)
        self.block_4_description.setObjectName("block_4_description")
        self.button_source_path = QtWidgets.QPushButton(self.block_4)
        self.button_source_path.setGeometry(QtCore.QRect(530, 80, 80, 25))
        self.button_source_path.setDefault(True)
        self.button_source_path.setObjectName("button_source_path")
        self.line_source_path = QtWidgets.QLineEdit(self.block_4)
        self.line_source_path.setGeometry(QtCore.QRect(10, 80, 520, 25))
        self.line_source_path.setInputMask("")
        self.line_source_path.setReadOnly(True)
        self.line_source_path.setObjectName("line_source_path")
        self.block_5 = QtWidgets.QFrame(self.centralwidget)
        self.block_5.setGeometry(QtCore.QRect(10, 545, 620, 120))
        self.block_5.setAccessibleName("")
        self.block_5.setAccessibleDescription("")
        self.block_5.setLocale(QtCore.QLocale(QtCore.QLocale.Polish, QtCore.QLocale.Poland))
        self.block_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.block_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.block_5.setLineWidth(2)
        self.block_5.setObjectName("block_5")
        self.block_5_title = QtWidgets.QLabel(self.block_5)
        self.block_5_title.setGeometry(QtCore.QRect(10, 5, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.block_5_title.setFont(font)
        self.block_5_title.setObjectName("block_5_title")
        self.block_5_description = QtWidgets.QLabel(self.block_5)
        self.block_5_description.setGeometry(QtCore.QRect(10, 35, 600, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.block_5_description.sizePolicy().hasHeightForWidth())
        self.block_5_description.setSizePolicy(sizePolicy)
        self.block_5_description.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.block_5_description.setFrameShape(QtWidgets.QFrame.Panel)
        self.block_5_description.setFrameShadow(QtWidgets.QFrame.Raised)
        self.block_5_description.setObjectName("block_5_description")
        self.button_segregation = QtWidgets.QPushButton(self.block_5)
        self.button_segregation.setGeometry(QtCore.QRect(10, 75, 120, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_segregation.setFont(font)
        self.button_segregation.setDefault(True)
        self.button_segregation.setObjectName("button_segregation")
        self.end_status = QtWidgets.QLabel(self.block_5)
        self.end_status.setGeometry(QtCore.QRect(180, 80, 200, 25))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.end_status.setFont(font)
        self.end_status.setTextFormat(QtCore.Qt.AutoText)
        self.end_status.setAlignment(QtCore.Qt.AlignCenter)
        self.end_status.setObjectName("end_status")
        self.end_button = QtWidgets.QPushButton(self.centralwidget)
        self.end_button.setGeometry(QtCore.QRect(510, 680, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.end_button.setFont(font)
        self.end_button.setLocale(QtCore.QLocale(QtCore.QLocale.Polish, QtCore.QLocale.Poland))
        self.end_button.setDefault(True)
        self.end_button.setFlat(False)
        self.end_button.setObjectName("end_button")
        self.setCentralWidget(self.centralwidget)

        #self.retranslateUi(MyWindow)
        QtCore.QMetaObject.connectSlotsByName(self)



        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Aplikacja Segregująca pliki BOM'u"))
        self.block_1_title.setText(_translate("MainWindow", "Krok 1"))
        self.block_1_description.setText(_translate("MainWindow", "Wybierz plik excel zawierający BOM i kliknij zweryfikuj aby sprawdzić czy jest on poprawny."))
        self.bom_button.setText(_translate("MainWindow", "Przeglądaj"))
        self.bom_verification_button.setText(_translate("MainWindow", "Zweryfikuj Poprawność"))
        self.bom_verification_info_text.setText(_translate("MainWindow", "..."))
        self.block_2_title.setText(_translate("MainWindow", "Krok 2"))
        self.block_2_description.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">Krok nie jest obowiązkowy. Kliknij przycisk aby program automatycznie policzył i wprowadził do arkusza Qty_Total.              Upewnij się, że plik nie jest obecnie otwarty.</p></body></html>"))
        self.qty_calculation_button.setText(_translate("MainWindow", "Policz Qty_Total"))
        self.bom_verification_info_text_2.setText(_translate("MainWindow", "..."))
        self.block_3_title.setText(_translate("MainWindow", "Krok 3"))
        self.block_3_description.setText(_translate("MainWindow", "Podaj ściezkę do miejsca gdzie bedą kopiowane posegregowane pliki i gdzie będzie zapisana lista brakujących plików."))
        self.button_destination_path.setText(_translate("MainWindow", "Przeglądaj"))
        self.block_4_title.setText(_translate("MainWindow", "Krok 4"))
        self.block_4_description.setText(_translate("MainWindow", "Podaj ściezkę do lokalizacji, z której będą kopiowane pliki. Program przejrzy wszystkie podfoldery tego folderu."))
        self.button_source_path.setText(_translate("MainWindow", "Przeglądaj"))
        self.block_5_title.setText(_translate("MainWindow", "Krok 5"))
        self.block_5_description.setText(_translate("MainWindow", "Kliknij przycisk Segreguj aby posegregować pliki zgodnie z podanymi wyżej danymi."))
        self.button_segregation.setText(_translate("MainWindow", "Segreguj"))
        self.end_status.setText(_translate("MainWindow", "Ukończono segregacje!!!"))
        self.end_button.setText(_translate("MainWindow", "Zakończ"))

        self.bom_button.clicked.connect(self.bom_button_clicked)
        self.bom_verification_button.clicked.connect(self.bom_verification_button_clicked)
        self.qty_calculation_button.clicked.connect(self.qty_calculation_button_clicked)
        self.button_destination_path.clicked.connect(self.button_destination_path_clicked)
        self.button_source_path.clicked.connect(self.button_source_path_clicked)
        self.button_segregation.clicked.connect(self.button_segregation_clicked)
        self.end_button.clicked.connect(self.end_button_clicked)

        self.bom_path = 'null'

    def bom_button_clicked(self):
        self.bom_path = QFileDialog.getOpenFileName(self, "Select File Name:", "D:\PROGRAMOWANIE", " Excel files (*.xlsx *.xls)")
        print(self.bom_path)
        self.line_bom_path.setText(self.bom_path[0])
        font = QtGui.QFont()
        font.setItalic(False)
        self.line_bom_path.setFont(font)
        return self.bom_path

    def bom_verification_button_clicked(self):
        print('bom_verification button wcisiniety')

        if self.bom_path == 'null':
            print("nie ma zmiennej bom path")
            self.bom_verification_info_text.setText('NIE WYBRANO ŻADNEGO PLIKU ZAWIERAJĄCEGO BOM!!!')
        else:
            print("jest zmienna bom path")
            print(self.bom_path[0])
            path = self.bom_path[0]
            try:
                item_number, part_number, qty, qty_total, tch1, tch2, tch3, rysunek, max_row = excel_check(path)
                if part_number and tch1 and tch2 and tch3 and rysunek and max_row:
                    self.bom_verification_info_text.setText('Wybrano poprawny plik BOM. Możesz przejść do kolejnego kroku.')
            except:
                print('plik nie jest poprawny')
                self.bom_verification_info_text.setText('Wybrany plik jest niepoprawny.')



    def qty_calculation_button_clicked(self):
        print('qty calculation button wcisniety')


    def button_destination_path_clicked(self):
        print('destinatination path button wcisniety')

    def button_source_path_clicked(self):
        print('source path button wcisniety')

    def button_segregation_clicked(self):
        print('button segregation wcisniety')

    def end_button_clicked(self):
        sys.exit(app.exec_())

def window():
    app = QApplication(sys.argv)
    win = MyWindow()
    win.show()
    sys.exit(app.exec_())

window()

# # pobranie linku do folderu skąd będą kopiowane wszystkie pliki:
# print("\n")
# print("=" * 60)
# print("\n")
# source = input("Podaj scieżkę do miejsca, z którego będą kopiowane pliki.\n"
#                "Zostaną przeszukane wszystie foldery i podfoldery tej lokalizacji.\n ====>")
# print("=" * 60)
#
# # pobranie linku do foledru gdzie jest bom i beda kopiowane pliki:
# destination = input("Podaj scieżkę do pliku BOM, tutaj zostaną skopiowane posegregowane pliki.\n"
#                     " Upewnij się, że w folderze jest plik .xlsx, zawiera w nazwie'BOM'"
#                     " i jest zgodny z szablonem.\n ====>")
# print("=" * 60)
#
# # nazwa pliku tekstowego z brakujacymi plikami
# txt_file_name = "Lista_brakujacych_plikow.txt"
#
# if finding_bom(destination):
#     bom_path = finding_bom(destination)
#     print("=" * 60)
#     print(" Znaleziono plik z BOMem:\n"
#           " Dokładna ścieżka do pliku z BOMem to:\n")
#     print("====>   " + bom_path + "   <====")
#     print("\n" + "=" * 60 + "\n")
# else:
#     print('bom nie został znaleziony')
#
# #jeżeli został znaleziony plik z BOMem to otwieramy go i pobieramy dane o interesujacych nas kolumnach:
# try:
#     print("Pobieranie danych o wierszach i kolumnach z pliku excel.")
#     part_number, tch1, tch2, tch3, rysunek, max_row = excel(bom_path)
#     print("-" * 60)
# except:
#     print("Nie udało się pobrać danych z pliku excel, sprawdź czy zgadza się z szablonem.")
#
# #jeżeli pobrano dane z bomu to tworzymy foldery i wrzucamy do nich pliki:
# try:
#     print("Segregacja plików zgodnie z obróbkami w pliku excel.")
#     no_file_in_source = file_segregation(source,destination, bom_path, part_number, tch1, tch2, tch3, rysunek, max_row)
#     print("-" * 60)
# except:
#    print("Wystapił problem w trakcie segregacji.")
#
# #jezeli udało się posegregować pliki to wynikiem jest tabela z brakującymi elementami, poniższa funkcje wrzuca te dnae do pliku tekstowego
# try:
#     print("Zapis brakujących plików do pliku tekstowego: '" + txt_file_name + "'.")
#     txt_file_creation(destination, no_file_in_source, txt_file_name)
#     print("-" * 60)
# except:
#    print("Nie udało się zapisać danych o brakujących elementach do pliku.")